name: supermarket_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  dson_adapter:
    git:
      url: https://github.com/ldantascruz/dson_adapter.git
      ref: 93f7bd73c7c64eec56530f9174a61b3f2013177f
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.1.1
  get: ^4.6.6
  jwt_decoder: ^2.0.1
  mask_text_input_formatter: ^2.9.0
  timezone: ^0.9.3
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

flutter_launcher_icons:
  #GLOBAL
  image_path: "assets/images/icon.png"
  #IOS
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  # ANDROID
  android: true
  adaptive_icon_background: "#FFFFFF"