name: Build APK

on:
  release:
    types:
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Rename APK
        working-directory: ./build
        run: |
          mv ./app/outputs/flutter-apk/app-release.apk ./riit-personal-${{ github.ref_name }}.apk
      - uses: actions/upload-artifact@v4
        with:
          name: supermarket-${{ github.ref_name }}.apk
          path: ./build/supermarket-${{ github.ref_name }}.apk
